# Generated by Django 3.1.2 on 2020-10-25 15:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30, null=True, verbose_name='Имя узла')),
                ('name', models.CharField(default='Нет данных', max_length=100, null=True, verbose_name='Название устройства')),
                ('ipaddr', models.CharField(default='Нет данных', max_length=20, null=True, verbose_name='IP адрес')),
                ('status', models.CharField(default='Нет данных', max_length=30, null=True, verbose_name='Состояние')),
                ('inv_num', models.CharField(default='Нет данных', max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{15}$')], verbose_name='Инвентарный номер')),
                ('serial_num', models.CharField(default='Нет данных', max_length=30, null=True, verbose_name='Серийный номер')),
                ('location', models.TextField(choices=[('Корпус 24A', 'Корпус A'), ('Корпус 20B', 'Корпус B'), ('Корпус 12C', 'Корпус C'), ('Корпус 20D', 'Корпус D'), ('Корпус 12E', 'Корпус E')], null=True, verbose_name='Местоположение')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('update_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='DeviceStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата')),
                ('printed_count', models.IntegerField(null=True, verbose_name='Количество отпечатанных страниц')),
                ('black_cart_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименование черного картриджа')),
                ('black_tonerlevel', models.IntegerField(blank=True, null=True, verbose_name='Уровень черного тонера')),
                ('cyan_tonerlevel', models.IntegerField(blank=True, null=True, verbose_name='Уровень голубого тонера')),
                ('mag_tonerlevel', models.IntegerField(blank=True, null=True, verbose_name='Уровень малинового тонера')),
                ('yel_tonerlevel', models.IntegerField(blank=True, null=True, verbose_name='Уровень желтого тонера')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device')),
            ],
        ),
    ]
