# Generated by Django 3.1.2 on 2020-10-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201026_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedetail',
            name='hostname',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя узла'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='Нет данных', max_length=200, null=True, verbose_name='Название устройства'),
        ),
    ]
