# Generated by Django 3.1.2 on 2020-10-26 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201026_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['hostname'], 'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='devicedetail',
            options={'ordering': ['-update_date']},
        ),
        migrations.AlterField(
            model_name='device',
            name='inv_num',
            field=models.CharField(default='1014000000', max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{15}$')], verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='device',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='devicedetail',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
    ]
