# Generated by Django 3.1.2 on 2020-10-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201027_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_num',
            field=models.CharField(default='Нет данных', max_length=50, null=True, verbose_name='Серийный номер'),
        ),
    ]
