# Generated by Django 3.1.2 on 2020-11-03 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201030_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=30, verbose_name='Имя узла'),
        ),
        migrations.AlterField(
            model_name='device',
            name='inv_num',
            field=models.CharField(default='1014000000', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{15}$', 'Требуется указать номер в виде 15 цифр')], verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.TextField(choices=[(None, 'Без расположения'), ('Корпус 24A', 'Корпус A'), ('Корпус 20B', 'Корпус B'), ('Корпус 12C', 'Корпус C'), ('Корпус 20D', 'Корпус D'), ('Корпус 12E', 'Корпус E')], default='', verbose_name='Местоположение'),
        ),
    ]
